'use strict';

// =============================================================================
// Generate the release notes for the version actually being released.
//
//   node scripts/release-notes.js --tag vX.Y.Z [--installer <file>] [--out <file>]
//
// The notes are derived from the release identity (desktop/package.json plus the tag), from the
// SHA-256 of the exact installer file that will be published, and from the real Git history
// between the previous release tag and this one. Nothing is carried over from an earlier release
// and nothing is invented.
//
// `scripts/release.js` calls this at the end of a successful pipeline, so the file it publishes
// always states the version, the installer, the checksum and the changes of its own release;
// `.github/workflows/release.yml` publishes `desktop/dist/RELEASE-NOTES.md` as the release body,
// and the release gate re-verifies that file against the packaged installer.
// =============================================================================

const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const releaseVersion = require('./release-version');

const DESKTOP_DIR = path.resolve(__dirname, '..');
const REPO_ROOT = path.resolve(DESKTOP_DIR, '..');

function git(args, repoRoot) {
  const result = spawnSync('git', args, { cwd: repoRoot, encoding: 'utf8' });
  if (result.error || result.status !== 0) {
    return null;
  }

  return (result.stdout || '').trim();
}

/** The release tag before this one, taken from the repository's own tags (never guessed). */
function previousReleaseTag(repoRoot, tag) {
  const listed = git(['tag', '--list', 'v*.*.*', '--sort=-v:refname', '--merged', 'HEAD'], repoRoot);
  if (!listed) {
    return null;
  }

  const candidates = listed
    .split(/\r?\n/)
    .map((value) => value.trim())
    .filter((value) => value.length > 0 && value !== tag);

  return candidates.length > 0 ? candidates[0] : null;
}

/** The commit subjects between the previous release and this one (real history, no changelog). */
function changesSince(repoRoot, previousTag) {
  const range = previousTag ? `${previousTag}..HEAD` : 'HEAD';
  const log = git(['log', '--no-merges', '--pretty=format:%s', range], repoRoot);
  if (!log) {
    return [];
  }

  return log
    .split(/\r?\n/)
    .map((value) => value.trim())
    .filter((value) => value.length > 0);
}

/** Build the release-notes document. Exported so the pipeline and tests share one renderer. */
function renderNotes(context) {
  const changes = context.changes.length > 0
    ? context.changes.map((subject) => `* ${subject}`).join('\n')
    : `* No source changes were recorded between ${context.previousTag} and this release ` +
      '(release-integrity maintenance only).';
  const since = context.previousTag ? `\`${context.previousTag}\`` : 'the start of the project';

  return `# EmailAI ${context.version} - Release Notes

**Windows x64 · ${context.installer} · ${context.checksum}**

## Version identity

| Item | Value |
| --- | --- |
| Application version | \`${context.version}\` (from \`desktop/package.json\`) |
| Git tag | \`${context.tag}\` |
| Installer | \`${context.installer}\` |
| Checksum file | \`${context.checksum}\` |
| SHA-256 | \`${context.sha256}\` |
| Commit | \`${context.commit}\` |
| Platform | Windows x64, per-user NSIS installer, unsigned |

## Changes since ${since}

${changes}

## Validation

These notes are generated by \`desktop/scripts/release-notes.js\` at the end of the release
pipeline, from the release identity, the Git history above and the SHA-256 of the exact installer
file. The pipeline refuses to continue if any of these disagrees, so this document only exists for
a build that passed them:

* \`dotnet test EmailAI.slnx -c Release\` - the automated suite, fully offline.
* \`dotnet build EmailAI.slnx -c Release\` - 0 warnings / 0 errors.
* \`dotnet publish src/EmailAI.Api -c Release -r win-x64 --self-contained true\` - the bundled backend.
* \`electron-builder --win nsis\` - the installer named in this document.
* \`node scripts/verify-secrets.js\` - no secret, no development-only configuration, no non-placeholder endpoint.
* Version identity - Git tag = \`desktop/package.json\` version = installer name = installer metadata = checksum.

## Installer

| File | \`${context.installer}\` |
| --- | --- |
| SHA-256 | \`${context.sha256}\` |
| Verify a download | \`Get-FileHash .\\${context.installer} -Algorithm SHA256\` and compare it with \`${context.checksum}\` |

## Known limitations

* The installer is not code-signed (SmartScreen may warn) and installs per user, with no administrator rights.
* Secrets live in the Windows Credential Manager (the \`EmailAI/Exchange\` and \`EmailAI/AI\` targets),
  never in the installer, the settings document or a log.
* This release is Windows x64 only - there is no x86 or ARM64 build.
`;
}

// ------------------------------------------------------------------ the pipeline

/**
 * Write the release notes for a release. `installerPath` is the exact installer file that will be
 * published, so the checksum in the notes is that file's real SHA-256.
 */
function writeReleaseNotes({
  desktopDir = DESKTOP_DIR,
  repoRoot = REPO_ROOT,
  tag,
  installerPath = null,
  outPath = null,
  previousTag = null,
}) {
  const identity = releaseVersion.resolveVersionIdentity({ desktopDir, tag });
  const installer = installerPath || path.join(desktopDir, 'dist', identity.installer);
  if (!fs.existsSync(installer)) {
    throw new releaseVersion.ReleaseVersionError(
      `the installer ${installer} does not exist: generate the release notes after packaging the release.`);
  }

  const sha256 = releaseVersion.sha256(installer);
  const resolvedPreviousTag = previousTag || previousReleaseTag(repoRoot, identity.tag);
  const changes = changesSince(repoRoot, resolvedPreviousTag);
  const commit = git(['rev-parse', '--short', 'HEAD'], repoRoot) || 'unknown';
  const target = outPath || path.join(desktopDir, 'dist', 'RELEASE-NOTES.md');

  const text = renderNotes({
    version: identity.version,
    tag: identity.tag,
    installer: identity.installer,
    checksum: identity.checksum,
    sha256,
    commit,
    previousTag: resolvedPreviousTag,
    changes,
  });

  // The notes are checked against the same rules the release gate applies, so a file the gate
  // would reject is never written.
  releaseVersion.assertReleaseNotes(text, {
    version: identity.version,
    installer: identity.installer,
    checksum: sha256,
    label: 'the generated release notes',
  });

  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, text);

  return {
    path: target,
    version: identity.version,
    tag: identity.tag,
    installer: identity.installer,
    checksum: identity.checksum,
    sha256,
    previousTag: resolvedPreviousTag,
    changes,
  };
}

module.exports = {
  changesSince,
  previousReleaseTag,
  renderNotes,
  writeReleaseNotes,
};

// ------------------------------------------------------------------------ CLI

function parseArguments(argv) {
  const options = {
    desktop: DESKTOP_DIR,
    repoRoot: REPO_ROOT,
    tag: process.env.EMAILAI_RELEASE_TAG || null,
    installerPath: null,
    outPath: null,
    previousTag: null,
  };

  for (let index = 0; index < argv.length; index++) {
    const argument = argv[index];
    const value = (name) => {
      const next = argv[++index];
      if (typeof next !== 'string' || next.length === 0) {
        throw new releaseVersion.ReleaseVersionError(`${name} needs a value.`);
      }

      return next;
    };

    switch (argument) {
      case '--tag': options.tag = value(argument); break;
      case '--desktop': options.desktop = path.resolve(value(argument)); break;
      case '--installer': options.installerPath = path.resolve(value(argument)); break;
      case '--out': options.outPath = path.resolve(value(argument)); break;
      case '--previous-tag': options.previousTag = value(argument); break;
      case '--help': options.help = true; break;
      default:
        throw new releaseVersion.ReleaseVersionError(
          `unknown argument "${argument}".\n\n` +
          'usage: node scripts/release-notes.js --tag vX.Y.Z [--installer <file>] [--out <file>]');
    }
  }

  return options;
}

if (require.main === module) {
  try {
    const options = parseArguments(process.argv.slice(2));
    if (options.help) {
      console.log(
        'usage: node scripts/release-notes.js --tag vX.Y.Z [--installer <file>] [--out <file>] ' +
        '[--previous-tag <tag>]');
    } else {
      const written = writeReleaseNotes(options);
      console.log(`[ok]   release notes written: ${written.path}`);
      console.log(`       EmailAI ${written.version} · ${written.installer} · sha256 ${written.sha256}`);
      console.log(
        `       changes since ${written.previousTag || 'the start of the project'}: ` +
        `${written.changes.length}`);
      if (written.changes.length === 0) {
        console.log(
          '[warn] no commit subjects were found in that range - a shallow checkout cannot build the ' +
          'change list (the release workflow checks out the full history).');
      }
    }
  } catch (error) {
    if (error instanceof releaseVersion.ReleaseVersionError) {
      console.error('');
      console.error(`[FAIL] ${error.message}`);
      console.error('');
      console.error('FAIL: no release notes were written.');
      process.exitCode = 1;
    } else {
      throw error;
    }
  }
}


