<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>EwsApiProbe</RootNamespace>
    <AssemblyName>EwsApiProbe</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Exchange.WebServices.NETCore" Version="3.3.1" />
  </ItemGroup>

</Project>
